#!/bin/bash

# Set all stderr output to /dev/null
exec 2> /dev/null

WALLPAPERDIR="$HOME/Dropbox/Photos/Wallpapers"

while read file; do 
    WIDTH=$(sips -g pixelWidth "$file" | tail -1 | cut -d" " -f4)
    HEIGHT=$(sips -g pixelHeight "$file" | tail -1 | cut -d" " -f4)

    # Check if the file is a valid image, if not skip
    [ -z "$WIDTH" ] && continue

    # Test the ratio against my pre configured ones
    case $(echo "scale=3;$WIDTH / $HEIGHT" | bc) in
        .563)  folder="iPhone/5" ;;
        .666)  if [[ "$WIDTH" -ge "640" ]]; then
                    folder="iPhone/Retina" 
               else
                    folder="iPhone/Standard"
               fi
               ;;
        1.000) if [[ "$WIDTH" -gt "1600" ]]; then
                    folder="iPad/Retina" 
               else
                    folder="iPad/Standard"
               fi
               ;;
        *) if [[ "$WIDTH" -lt "$HEIGHT" ]]; then
                if [[ "$WIDTH" -ge "640" ]]; then
                    folder="iPhone/Retina/odd_ratio" 
                else
                    folder="iPhone/Standard/odd_ratio"
                fi
           else
                folder="Desktop" 
           fi
           ;;
    esac

    if [[ $folder != "Desktop" ]]; then
        folder="Gadgets/$folder"
    fi

    echo "Moving $file to $folder"
    mv "$file" "$WALLPAPERDIR/$folder/${WIDTH}x${HEIGHT}_$file"
done < <(ls *jpg *jpeg *png *bmp *JPG *JPEG *PNG *BMP)
